apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-tls
  namespace: nginx
spec:
  dnsNames:
    - nginx.leonschmidt.cloud
  secretName: example-cert-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer