name: Terraform apply

on:
  push:
    branches:
      - main

env:
  TERRAFORM_VERSION: 1.4.6

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/766712485593/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions@jenkins-389117.iam.gserviceaccount.com

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=output.tfplan

      - name: Publish Terraform Plan
        uses: actions/upload-artifact@v3
        with:
          name: output.tfplan
          path: /home/runner/work/gcp-jenkins/gcp-jenkins/output.tfplan

  apply:
    name: Terraform apply
    runs-on: ubuntu-latest
    needs: plan

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Terraform Plan
        uses: actions/download-artifact@v3
        with:
          name: output.tfplan
          path: /home/runner/work/gcp-jenkins/gcp-jenkins/

      - run: ls -lah

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/766712485593/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions@jenkins-389117.iam.gserviceaccount.com

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Init
        run: terraform init

      - run: ls -d */
      - run: ls -lah

      - name: Terraform Apply
        run: terraform apply -auto-approve /home/runner/work/gcp-jenkins/gcp-jenkins/output.tfplan
